// Code generated by "stringer -type=InquiryErrorCode"; DO NOT EDIT.

package errorcodes

import "strconv"

const _InquiryErrorCode_name = "FailedToParseInquiryJson"

var _InquiryErrorCode_index = [...]uint8{0, 24}

func (i InquiryErrorCode) String() string {
	if i < 0 || i >= InquiryErrorCode(len(_InquiryErrorCode_index)-1) {
		return "InquiryErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InquiryErrorCode_name[_InquiryErrorCode_index[i]:_InquiryErrorCode_index[i+1]]
}
