// Code generated by "stringer -type=TaskErrorCode"; DO NOT EDIT.

package errorcodes

import "strconv"

const _TaskErrorCode_name = "NoErrorFailedToParsetaskJSONNoTaskToEraseFailedToMakeARequestFailedToSendARequestFailedToReadRequestBody"

var _TaskErrorCode_index = [...]uint8{0, 7, 28, 41, 61, 81, 104}

func (i TaskErrorCode) String() string {
	if i < 0 || i >= TaskErrorCode(len(_TaskErrorCode_index)-1) {
		return "TaskErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskErrorCode_name[_TaskErrorCode_index[i]:_TaskErrorCode_index[i+1]]
}
